################################
### Zoom - By Justin Michaud ###
###   Default config file    ###
################################



####################################################
# The item that you left or right click to zoom in #
####################################################
MagicItem : BOW

###################################################################################################
# Use the left or right mouse button? If the plugin doesn't recognise the value, it assumes right #
###################################################################################################
Mouse_Button : left


#########
## End ##
#########